### PR TITLE
Omnibus PR with fixes for #333, #334, #335, and README updates

### LINKED ISSUE #335: Latest update using .asmdef breaks monobehavior components
Putting this here to be referenced later.

.asmdef breaks monobehavior components due to the editor-only nature of RCSG. Fixing this will either require a full project re-structure, or removal of .asmdef (not ideal either way).

In the meantime, for those having issues with this, just deleting the .asmdef should allow RCSG to function as it should.

Referenced issues:
- #333
- #334
- #332

### PR DESCRIPTION
**Pull request by Kerfuffles**
This PR fixes issues introduced with PR #333. It fixes #334 and closes #335. All changes that were not present in the release 7521cd7d1c2cc3b9d097d702567aedbd74b2c387 and were in #333 are here, as well.

**Changes introduced in #333:**
* The repo is now a package compatible with Unity Package Manager.
* Icons are embedded into a generated class, which reduces clutter in the texture browser.

**#333 fixes introduced in this PR:**
* The root folder of RealtimeCSG is now found using a directory search, instead of a file search. This removes the need for finding  `RealtimeCSG.asmdef` or a text document.

**#334 and #335 fixes:**
* `UNITY_EDITOR` define was added to the define constraints of `RealtimeCSG.asmdef`, and compatible platforms were defined, which fixes player builds failing due to editor classes included in build.

**Other changes:**
* Readme updated to include information on how to import the project with supported methods, and formatting adjusted to be easier to read.
* Included information on how to contribute to the project
* Included changes from #341

### CODE REVIEW

**Comment by LogicalError** [comment]
Sorry made some tiny modifications to 2 files, didn't notice your PR until after that

**Review by LogicalError — APPROVED** [review]

**Comment by Kerfuffles** [comment]
> Sorry made some tiny modifications to 2 files, didn't notice your PR until after that

No worries! I'll just bring the changes over when I have time.

**Comment by Kerfuffles** [comment]
All merge conflicts were resolved. If all is good, then I'll go ahead and merge the changes + create a release.

**Comment by Kerfuffles** [comment]
Just occurred to me that there should probably be a FAQs section in the readme. I'll add that in after work later today. Beyond that, that is all the things I can think of that needed fixing or adding, unless someone else brings something up.

**Comment by Kerfuffles** [comment]
Trying this PR in an actual project seems to cause an extended load time, that seems to go on infinitely (freezes the editor basically). I'm looking into changing how `MaterialUtility.CreateRenderPipelineVersionOfDefaultMaterial(Material, string)` handles getting paths for things, as it appears that finding directories or files is extremely slow with a lot of folders (sensible). Due to this, I'm going to mark this PR as a draft until I can fully fix this problem. Additionally, it appears to not work as a local package (cannot find folder), and I'm hoping that fixing the above will also fix that.

**Comment by Kerfuffles** [comment]
Farther digging provides that the hang is related to render pipelines and material generation. Looking into how to fix this.

**Comment by Kerfuffles** [comment]
Last commit *should* hopefully fix the aforementioned material generation issue and allow RCSG to work with RPs properly, again.

**Review by LogicalError — APPROVED** [review]

**Pull request merged**
