### PR TITLE
Convert project to Plugins/ folder only

### LINKED ISSUE #300: [FR] Avoid hardcoded paths in the code to allow moving of the asset anywhere in the project
It would be nice to have all icons / textures locations to be handled by the Unity's asset database.
Right now there's some material textures and icons that will break / lead to errors if the asset is moved anywhere else than assets folder or will make them invisible.

This prevents proper project structure.
E.g. RealtimeCSG cannot be moved to /Assets/_ThirdParty/RealtimeCSG without source code modifications.

### LINKED ISSUE #332: Make repo only the Plugins/RealtimeCSG folder
More of an note for myself, so it can be referenced in a PR at a later time.

This would remove the entirety of the unity project, and leave only the `Plugins/RealtimeCSG` folder, to make onboarding for new users easier/more obvious as to what is needed when importing RealtimeCSG, or for existing users to just simply clone the repo into their project, instead of having to manually copy the files each time something is changed/updated.

### PR DESCRIPTION
**Pull request by Kerfuffles**
This PR:
closes #300 
closes #332

It also removes some clutter from the texture browser.

Biggest changes are that the entire repo is no longer a unity project, but just the RealtimeCSG folder. Referencing #332, this should make onboarding a bit smoother, and possibly make updating easier for others who don't make any local changes to RCSG.

Additionally, icons are now embedded in a script (I added a zip with the original icons, and a script generator to update embedded content). This does not change how RealtimeCSG handles icons, but only migrates it to the embedded system. In order to use the script generator, one would simply drop the icons into `Resources/RealtimeCSG/Icons/` anywhere in the project, press "Find Icons", and then press "Convert". A new version of `EmbeddedAssets` will be generated in `RealtimeCSG/Plugins/Editor/Scripts/Data/Generated/Icons/`. This path will always point to the RealtimeCSG folder so that it is always generated in the correct location.

### CODE REVIEW

**Review by LogicalError — APPROVED** [review]

**Comment by Casey-Hofland** [comment]
The inclusion of the package.json is interesting to me. Are you planning on converting Realtime CSG to a package at a later stage?

**Comment by Kerfuffles** [comment]
> The inclusion of the package.json is interesting to me. Are you planning on converting Realtime CSG to a package at a later stage?

This PR does exactly that

**Comment by Casey-Hofland** [comment]
> This PR does exactly that

I see, my bad, usually packages don't have a Plugins folder. This one, for example, would normally directly put the API, Editor and Runtime folder at the root.

By chance I also happened to notice that the project now also contains an .asmdef, which is a welcome inclusion. However, note that a second .asmdef needs to be created in the Editor folder, as they ignore conventional folder naming rules. Without an Editor .asmdef, it becomes impossible to build, so I urge that this is looked at quickly.

**Comment by Kerfuffles** [comment]
> By chance I also happened to notice that the project now also contains an .asmdef, which is a welcome inclusion. However, note that a second .asmdef needs to be created in the Editor folder, as they ignore conventional folder naming rules. Without an Editor .asmdef, it becomes impossible to build, so I urge that this is looked at quickly.

The repo is intended to also be used by older versions of unity (back to 5.4), not only newer versions that support package manager, so `Plugins/` is necessary, and the format of the repo is intentional. The fix for not being able to build is very simple, and something I had missed when checking everything over. Just change the platform of the .asmdef to editor only. RCSG only generates a mesh, which is the only thing that ends up in the build, so no scripts are built when the player is built.

**Comment by Kerfuffles** [comment]
See #334. The mentioned issue has been fixed, as far as I can tell. Please add any additional comments there, thanks.

**Pull request merged**
